name: Build PageOS ISO

on:
  workflow_dispatch:
    inputs:
      name:
        description: "OS name"
        required: false
        default: "pageos"

concurrency:
  group: "测试"
  cancel-in-progress: true

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: swaybien/pageos

      - name: Setup actions environment
        run: ./scripts/gh_acions_setup.bash

      - name: Run build script
        run: sudo -u builder ./build.bash --noconfirm

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.name || 'pageos' }}
          path: target/*.iso
          compression-level: 9 # maximum compression
          retention-days: 5
